nirum-lang/nirum

Dockerfile
Add `Dockerfile` for build a docker image.
=> Dockerize Nirum

src/Nirum/Targets/Python.hs, test/Nirum/Targets/PythonSpec.hs
=> Implement Client target

src/Nirum/Constructs/Annotation.hs, test/Nirum/ParserSpec.hs
It fixes the bug that `toCode` didn't escape some characters which can make the printed result can't parse, while converting `Annotation`.
Examples:
```
$ stack exec ghci
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
Prelude> :seti -XOverloadedStrings
Prelude> import qualified Data.Text as T
Prelude T> import Nirum.Constructs.Annotation
Prelude T Nirum.Constructs.Annotation> let printCode = putStrLn . T.unpack . toCode
Prelude T Nirum.Constructs.Annotation> printCode $ Annotation "a" (Just "b\nc\td\"")
@a("b\nc\td\"")
```
=> Escape some characters of annotation metadata

nirum.cabal, src/Nirum/Constructs/Annotation.hs, src/Nirum/Constructs/Annotation/Internal.hs, src/Nirum/Constructs/Declaration.hs, src/Nirum/Constructs/Module.hs, src/Nirum/Constructs/Service.hs, src/Nirum/Constructs/TypeDeclaration.hs, src/Nirum/Parser.hs, src/Nirum/Targets/Python.hs, test/Nirum/Constructs/AnnotationSpec.hs, test/Nirum/Constructs/ModuleSpec.hs, test/Nirum/Constructs/ServiceSpec.hs, test/Nirum/Constructs/TypeDeclarationSpec.hs, test/Nirum/PackageSpec.hs, test/Nirum/ParserSpec.hs, test/Nirum/Targets/PythonSpec.hs
This PR suggests to unify internal representations of doc comments and the annotation set, by treat doc comments as a `@doc("...")` annotation.
=> Unify docs into annotations

nirum.cabal, src/Nirum/Cli.hs, src/Nirum/Constructs/Annotation.hs, src/Nirum/Constructs/Annotation/Internal.hs, src/Nirum/Constructs/Declaration.hs, src/Nirum/Constructs/Identifier.hs, src/Nirum/Constructs/Module.hs, src/Nirum/Constructs/ModulePath.hs, src/Nirum/Constructs/Name.hs, src/Nirum/Constructs/Service.hs, src/Nirum/Constructs/TypeDeclaration.hs, src/Nirum/Constructs/TypeExpression.hs, src/Nirum/Parser.hs, src/Nirum/Targets/Python.hs, test/Nirum/CliSpec.hs, test/Nirum/Constructs/AnnotationSpec.hs, test/Nirum/Constructs/DeclarationSetSpec.hs, test/Nirum/Constructs/DeclarationSpec.hs, test/Nirum/Constructs/IdentifierSpec.hs, test/Nirum/Constructs/ModulePathSpec.hs, test/Nirum/Constructs/ModuleSpec.hs, test/Nirum/Constructs/NameSpec.hs, test/Nirum/Constructs/ServiceSpec.hs, test/Nirum/Constructs/TypeDeclarationSpec.hs, test/Nirum/Constructs/TypeExpressionSpec.hs, test/Nirum/PackageSpec.hs, test/Nirum/ParserSpec.hs, test/Nirum/Targets/PythonSpec.hs, test/Nirum/VersionSpec.hs
`OverloadedStrings` GHC extension is used globally in Nirum source code, so most of files have `{# LANGUAGE OverloadedStrings #}` pragma. It's too repetitive so I suggest to make this extensions as a default and remove the pragmas.
=> Set -XOverloadedStrings globally and reduce {# LANGUAGE #} pragma

nirum.cabal, src/Nirum/Constructs/Annotation.hs, src/Nirum/Constructs/Annotation/Internal.hs, src/Nirum/Constructs/Declaration.hs, src/Nirum/Constructs/Docs.hs, src/Nirum/Constructs/Module.hs, src/Nirum/Constructs/Service.hs, src/Nirum/Constructs/TypeDeclaration.hs, src/Nirum/Package.hs, src/Nirum/Parser.hs, test/Nirum/Constructs/DeclarationSetSpec.hs, test/Nirum/Constructs/DocsSpec.hs, test/Nirum/Constructs/ServiceSpec.hs, test/Nirum/Constructs/TypeDeclarationSpec.hs, test/Nirum/ParserSpec.hs, test/Nirum/Targets/PythonSpec.hs, test/Util.hs
=> Merge docs into annotations completely

nirum.cabal, src/Nirum/CodeGen.hs, src/Nirum/Targets/Python.hs, test/Nirum/CodeGenSpec.hs, test/Nirum/Targets/PythonSpec.hs
This is a preparation of #50, to insert the information which version of Python code will be generated, in the code generation progress.
=> Generalize CodeGen to use it for other targets

src/Nirum/Parser.hs, test/Nirum/ParserSpec.hs
This patch fixes #69.
The parser previously has a bug disallowing any whitespaces (including newline) right before and right after `union` tags' parentheses.  For example, the previous parser doesn't accept the following `union` declaration:
```nirum
union shape
= circle (  // ⬅️ Newline/whitespaces not allowed ➡️
point origin,
offset radius,
// ⬅️ Newline/whitespaces not allowed ➡️
)
| rectangle (  // ⬅️ Newline/whitespaces not allowed ➡️
point upper-left,
point lower-right,
// ⬅️ Newline/whitespaces not allowed ➡️
)
| none
;
```
=> Allow spaces right before/after tag parentheses

src/Nirum/Constructs/Module.hs, src/Nirum/Constructs/TypeDeclaration.hs, src/Nirum/Constructs/TypeExpression.hs, src/Nirum/Package.hs, src/Nirum/Parser.hs, test/Nirum/Constructs/ModuleSpec.hs, test/Nirum/Constructs/TypeDeclarationSpec.hs, test/Nirum/PackageSpec.hs, test/Nirum/ParserSpec.hs, test/Nirum/Targets/PythonSpec.hs
=> Completely implement annotations

src/Nirum/Targets/Python.hs, test/Nirum/Targets/PythonSpec.hs
=> Generate __hash__ on python as well

test/Nirum/Targets/PythonSpec.hs
Although [raising `ValueError`/`TypeError` seems inappropriate for deserialization errors][1], I created a hotfix of incompatibility with upstream nirum-python.  This incompatibility blocks #78 and #79 to be merged by breaking CI builds.
[1]: https://gitter.im/spoqa/nirum?at=57e2df5818291e10488f32c3
=> Hotfix of incompatibility with upstream nirum-python

examples/shapes.nrm
At the very early of Nirum, it doesn't have distinct keywords like `record`/`union`/`record` but only one keyword: `value`.  What the docs of examples/shapes.nrm explain about is that.
=> Update outdated docs about the ancient language

.travis.yml, appveyor.yml, docs/serialization.md, examples/shapes.nrm, src/Nirum/Constructs/Identifier.hs, src/Nirum/Constructs/TypeDeclaration.hs, src/Nirum/Parser.hs, src/Nirum/Targets/Python.hs, test/Nirum/Constructs/ModuleSpec.hs, test/Nirum/Constructs/TypeDeclarationSpec.hs, test/Nirum/ParserSpec.hs, test/Nirum/Targets/PythonSpec.hs
Fixes #65 and depends on spoqa/nirum-python#41.  (So the builds will be broken until spoqa/nirum-python#41 gets merged.)
Renamed `boxed` keyword to `unboxed` as I suggested from #65.  Also adjusted docs and examples.
=> Rename boxed to unboxed

nirum.cabal, src/Nirum/Constructs/Annotation.hs, src/Nirum/Constructs/Annotation/Internal.hs, src/Nirum/Constructs/Docs.hs, src/Nirum/Constructs/Identifier.hs, src/Nirum/Constructs/Service.hs, src/Nirum/Package/ModuleSet.hs, src/Nirum/Targets/Python.hs, stack.yaml, test/Nirum/CodeGenSpec.hs
As the title says, this patch upgrades `stack`'s resolver from Stackage Nightly an-arbitrary-date something to [LTS Haskell 8.4][1].  Although it's LTS, it's even newer than the previous resolver.
As HLint upgraded, it now suggests all single field record to be `newtype` instead of `data`.  So I followed the suggestion as well.  The most of diffs are caused by this.
Lastly, I removed duplicated version specifiers of the common dependencies between `library` and `test-suite spec`.
[1]: https://www.stackage.org/lts-8.4
=> Upgrade resolver to Stackage Haskell LTS 8.4

src/Nirum/Constructs/ModulePath.hs, src/Nirum/Package/ModuleSet.hs, src/Nirum/Targets/Python.hs, test/Nirum/Constructs/ModulePathSpec.hs, test/Nirum/Package/ModuleSetSpec.hs, test/Nirum/Targets/PythonSpec.hs, test/python/setup_test.py
=> Add ancestors of packages to packages in setup.py

README.md, src/Nirum/Cli.hs, src/Nirum/Targets.hs
Although #99 made Nirum's internals possible to extend targets, it didn't expose its extensiblity to the user interface (CLI).
This patch added `-t`/`--target` option to specify the target language of the object. Also it prints the list of all available targets.
=> -t/--target option

src/Nirum/Cli.hs
=> Print error with exit code when error occured

README.md, appveyor.yml, nirum.cabal, src/Nirum/Cli.hs, test.sh
Use [optparse-applicative](https://haskell-lang.org/library/optparse-applicative) which one is suggested in #88. this PR close #88 as well.
=> Use optparse-applicative instead of cmdargs

README.md, nirum.cabal, src/Nirum/Cli.hs
Fixed several things that PR #111 missed:
- Remove cmdargs from `build-depends` as it's no more used since #111 introduced optparse-applicative.
- Update the CLI example on README.md as `-t`/`--target` became required.
- Restore the list of available targets on `-h`/`--help`.
=> Fix regressive things PR #111 missed

examples/pdf-service.nrm, nirum.cabal, src/Nirum/Targets/Docs.hs
I added more about types to generated docs e.g. field types, members, methods, parameter types.
=> Docs target now shows more details

src/Nirum/Targets/Python.hs, test.sh, test/Nirum/Targets/PythonSpec.hs, test/nirum_fixture/fixture/foo.nrm
There was a bug that Python 2 code generator had missed `import typing` even if some type expressions require it.  This patch fixed the bug #93.
=> Fix missing `import typing` on Python 2

examples/package.toml, src/Nirum/Package/Metadata.hs, src/Nirum/Targets/Python.hs, test/Nirum/Package/MetadataSpec.hs, test/Nirum/PackageSpec.hs, test/Nirum/Targets/PythonSpec.hs
This patch adds `minimum_runtime` option to Python target settings. The specified version goes to the generated `install_requires` list. Also the Nirum compiler now has its own minimum runtime version; see also `Nirum.Targets.Python.minimumRuntime` constant.
If `minimum_runtime` option specified by package.toml is older than compiler's minimum runtime version, or it's omitted, compiler's version is used instead.
Closes #118.
=> Add "minimum_runtime" option to Python target settings

docs/target/python.md, nirum.cabal, src/Nirum/Constructs/ModulePath.hs, src/Nirum/Package/Metadata.hs, src/Nirum/Targets/Python.hs, test/Nirum/Constructs/ModulePathSpec.hs, test/Nirum/Package/MetadataSpec.hs, test/Nirum/PackageSpec.hs, test/Nirum/Targets/PythonSpec.hs, test/nirum_fixture/package.toml, test/nirum_fixture/renames/test/foo.nrm, test/nirum_fixture/renames/test/foo/bar.nrm, test/python/renames_test.py, test/python/setup_test.py
This patch introduces a new option `targets.python.renames`.  It is a translation table of `ModulePath` to `ModulePath` and purposes to rename the matched module paths.  Here's an example (which motivated me to implement this):
```toml
[targets.python.names]
contract = "contract-schema"
```
It makes the root module `contract` to be compiled to Python package `contract_schema`.  See docs/target/python.md for more details.
=> Add renames option to Python target

nirum.cabal, src/Nirum/Constructs/Declaration.hs, src/Nirum/Constructs/Module.hs, src/Nirum/Constructs/Service.hs, src/Nirum/Constructs/TypeDeclaration.hs, src/Nirum/Docs/ReStructuredText.hs, src/Nirum/Package.hs, src/Nirum/Parser.hs, src/Nirum/Targets/Python.hs, test/Nirum/Constructs/DeclarationSetSpec.hs, test/Nirum/Docs/ReStructuredTextSpec.hs, test/Nirum/ParserSpec.hs, test/nirum_fixture/fixture/foo.nrm, test/python/docs_test.py
This patch makes Python target to generate docstrings from Nirum docs.  Markdown texts are translated to RST.
Closes #102.
=> Generate Python docstrings from docs

nirum.cabal, src/Nirum/Targets/Docs.hs, test/Nirum/Targets/DocsSpec.hs
=> Add title to module document for Docs target

examples/pdf-service.nrm, src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/annotation_test.py, test/python/service_test.py
https://github.com/spoqa/nirum/issues/38
=> Service methods should be possible to specify its error type 

examples/package.toml, nirum.cabal, src/Nirum/CodeBuilder.hs, src/Nirum/Targets.hs, src/Nirum/Targets/JavaScript.hs, test/Nirum/CodeBuilderSpec.hs, test/Nirum/Targets/JavaScriptSpec.hs
=> WIP: Add stub of JavaScript target

src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/typeconversion_test.py, tox.ini
it fixes spoqa/nirum-python#49. this PR propose convert a type that could be mutable to immutable type always rather than raise error on runtime.
=> Convert mutable type which is unhasable to immutable types

nirum.cabal, src/Nirum/Cli.hs
=> -w/--watch option

src/Nirum/Targets/Python.hs
The previous versions of the Python runtime has several bugs that impact on the use of services.
=> Require Python runtime version 0.5.1 or higher

src/Nirum/Targets/Python.hs, test/Nirum/Targets/PythonSpec.hs
Generate `import`s using aliasing (i.e. `as`) instead of referring private names.  The Python target had generated `import`s like the following:
```python
from nirum.datastructures import list_type
```
This patch makes it to generate the following code instead:
```python
from nirum.datastructures import List as list_type
```
=> Python: aliased imports

.travis.yml, README.md, appveyor.yml, src/Nirum/Constructs/Service.hs, src/Nirum/Targets/Python.hs, test/python/primitive_test.py, tox.ini
This compiler patch is for suggested new transport layer spoqa/nirum-python#79 and related other things.  It also is required by another patch on nirum-python spoqa/nirum-python#92 and need to be merged first.
Key changes:
- Generated constructors of service clients became to take a `nirum.transport.Transport` instance.
- Followed renamed/moved import paths of the runtime classes (e.g. `nirum.rpc.Service` → `nirum.service.Service`).
- The way to avoid name collision between generated types and runtime classes is changed.  The runtime library had provided alternative names like `service_type` for `Service` and generated imports had been like `from nirum.rpc import service_type`, but it's now `from nirum.service import Service as service_type`.
As its build requires transport features made …
=> Make generated Python codes refactored for new transport layer

.travis.yml, appveyor.yml
As spoqa/nirum-python#92 was merged, we don't need `DEVRUNTIME_*` settings anymore.
=> Remove temporary DEVRUNTIME_* settings

src/Nirum/Targets/Docs.hs, test/Nirum/Targets/DocsSpec.hs
=> Add documents for HTML target

examples/shapes.nrm, src/Nirum/Parser.hs, test/Nirum/ParserSpec.hs
Fixes #153.
Like record docs, union tag docs also now can be in parentheses e.g.:
```nirum
union U
= T1 ()
| T2 (
)
;
```
=> Union tag docs now can be in parentheses

Dockerfile
`nirum` couldn't be executed because nirum binary didn't be placed on
`PATH`. so i added `--copy-bins` option to copy binary into `PATH`
@dahlia @Kroisse @AiOO @ipdae  help me!
=> Copy binary to PATH

src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/primitive_test.py
=> Defaulting None for optional fields

src/Nirum/Targets/Docs.hs
=> Improve document design

src/Nirum/Package/Metadata.hs, src/Nirum/Targets/Python.hs, test/Nirum/CodeBuilderSpec.hs, test/Nirum/Package/MetadataSpec.hs, test/Nirum/PackageSpec.hs, test/Nirum/Targets/PythonSpec.hs, test/nirum_fixture/package.toml, test/python/setup_test.py
This patch adds the description field to package metadata. (#100)
=> Add description field to package metadata

docs/package.md, src/Nirum/Package/Metadata.hs, src/Nirum/Targets/Python.hs, test/Nirum/CodeBuilderSpec.hs, test/Nirum/Package/MetadataSpec.hs, test/Nirum/PackageSpec.hs, test/Nirum/Targets/PythonSpec.hs, test/nirum_fixture/package.toml, test/python/setup_test.py
This patch adds the license field to package metadata. (#100)
=> Add license field to package metadata

docs/package.md, src/Nirum/Package/Metadata.hs, src/Nirum/Targets/Python.hs, test/Nirum/CodeBuilderSpec.hs, test/Nirum/Package/MetadataSpec.hs, test/Nirum/PackageSpec.hs, test/Nirum/Targets/PythonSpec.hs, test/nirum_fixture/package.toml
This patch adds the keywords field to package metadata. (#100)
I named keywords metadata to `packageKeywords` because of a conflict with Python keywords in `Nirum/Targets/Python.hs`.
=> Add keywords field to package metadata

src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/primitive_test.py
Fix https://github.com/spoqa/nirum/issues/185.
Add `_` at the end of member name when it is duplicated with Python keyword (eg. `mro`).
=> Rename mro not to overlap with Python keyword

src/Nirum/Parser.hs, test/Nirum/ParserSpec.hs
Fixes <https://github.com/spoqa/nirum/issues/184>.
There had been a parser bug that bare identifiers (i.e. unquoted identifiers) cannot start with reserved keywords, e.g. `types` (`type` is reserved), `enumeration` (`enum` is reserved`).  This patch fixes the bug.
=> Bare identifiers now can start with reserved keywords as their prefix

docs/annotation.md, lint.sh, src/Nirum/Constructs/Annotation.hs, src/Nirum/Constructs/Annotation/Internal.hs, src/Nirum/Constructs/Docs.hs, src/Nirum/Parser.hs, test/Nirum/Constructs/AnnotationSpec.hs, test/Nirum/Constructs/ServiceSpec.hs, test/Nirum/Constructs/TypeDeclarationSpec.hs, test/Nirum/ParserSpec.hs
As #178 suggested, I made annotation arguments multiple.  To simplify the rule unnamed arguments became unsupported; thus every argument has its parameter name.  `@docs`, an internal annotation that represents docs comments, also have a parameter named `docs`.  Annotations without parentheses are equivalent to zero arguments.
Also wrote some docs about annotations.  I believe the docs is enough substitution of explanation for this pull request.
=> Named and multiple arguments for annotations

src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/primitive_test.py
- As I suggested from <https://github.com/spoqa/nirum-python/issues/34#issuecomment-247835731>, now generated Python classes have `__nirum_type__` attribute which contains one of `'unboxed'`/`'enum'`/`'record'`/`'union'`/`'service'`.  The future versions of Python runtime library would be able to utilize this rather than diagnostics using `isinstance()`/`hasattr()` queries. See also examples on `test_nirum_type()`.
- Also as I suggested from the same comment above, now union classes have an immutable map named `__nirum_tags__` that keys are tags and values are class objects.  See also examples on `test_nirum_tag_classes()`.
- Since the bug #185 was also applicable to union tag enums, also fixed it.  See also `test_union_reserved_keyword_for_tag()` to reproduce the bug.
=> Several changes on RTTI metadata for Python target

src/Nirum/Targets/Python.hs, test/python/primitive_test.py
Implemented an essential part of the suggestion made by #68.  Now the canonical name of every generated tag class is under its union class (e.g. `Rectangle` → `Shape.Rectangle`).  As it's still undetermined whether or not to leave unqualified name, I remained it as it had been for backward compatibility.
=> Qualify tag classes under type classes

src/Nirum/CodeBuilder.hs, src/Nirum/Package.hs, src/Nirum/Targets/Docs.hs, src/Nirum/Targets/Python.hs, src/Nirum/TypeInstance/BoundModule.hs, test/Nirum/CodeBuilderSpec.hs, test/Nirum/PackageSpec.hs, test/Nirum/Targets/PythonSpec.hs, test/Nirum/TypeInstance/BoundModuleSpec.hs
`BoundModule` and functions dealing with it get moved to a separated module named `Nirum.TypeInstance.BoundModule` which is its own.
In the later pull requests, I'm going to define some intermediate representation for types (which already evaluated every `TypeExpression` of them) in the `Nirum.TypeInstance` module.
=> Move BoundModule and functions for it to a separated module

examples/pdf-service.nrm, lint.sh, src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/annotation_test.py
Since we need metadata of annotations on service class to route HTTP paths, i added `__nirum_method_annotations__` property.
`__nirum_method_annotations__` contain metadata of method annotations as nirum.datastaructures.Map type because it have to be immutable data.
=> Compile service method annotation

src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/annotation_test.py
Unlike annotation names or annotation parameter names, annotation argument values should be able to contain non-ASCII Unicode characters.  This fixes the Python target to correctly translate annotation argument values to Unicode string literals instead of byte string literals.
=> Make annotation argument values able to contain Unicode characters

src/Nirum/Targets/Docs.hs
Just what the title says. Fixes #198.
=> Fix #198 Add delimiter for method parameters. 

src/Nirum/Parser.hs, test/Nirum/ParserSpec.hs
This patch makes the parser accepts import names with a trailing comma or in multilines that hadn't been allowed, e.g.:
```nirum
import foo.baz (
c,
d,
);
```
=> Make import names can have a trailing comma and be multiline

src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/service_test.py, tox.ini
This patch makes Python target to generate standalone serializers for generated types so that these are independent from `nirum.serialize.serialize_*()` functions implemented by nirum-python runtime library.
Service clients also became free from `serialize_meta()` function.
=> Runtime free serializers

src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/primitive_test.py
This fixes a bug that PR #201 introduced.
When a record or a union tag has an optional field, the generated Python serializers had been able to unexpectedly crash if the field contains `None`.
See also the added test case.
=> Fix optional types serializer to be null-safe

src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/primitive_test.py
Generated serializers had to generated temporary local variables and referred to it, but sometimes these had had an invalid name (e.g., `__self.field_name__elem__`).  This patch fixes the bug besides the following bugs:
-  A bug that map types had been serialized in JSON to `{k: v}` while these should be `[{"key": k, "value": v}]`.
-  A potential bug that temporary variables had been leaked to their outer scope in Python 2 since local variables in list comprehensions aren't isolated in Python 2.  See also [*What's New in Python 3.0*][1]:
> Also note that list comprehensions have different semantics: they are closer to syntactic sugar for a generator expression inside a [`list()`][2] constructor, and in particular the loop control variables are no longer leaked into the surrounding scope. …
=> Fix the way to mangle temporary local variables used by serializers

src/Nirum/Targets/Python.hs
Use Heterocephalus to generate unboxed types, enum types, and type aliases.
=> More Heterocephalus on Python code generation

src/Nirum/Targets/Python.hs
It's a bugfix of regression made by my previous PR #211.  As `typinng.Type[T]` has been available since Python 3.5.2, the previous versions raise `AttributeError`.  Unfortunately, we currently cannot use that generic abstract type.
=> Avoid typing.Type[T] for compatibility with Python < 3.5.2

.travis.yml
As our macOS build is quite fragile and it's due to Travis CI's own problem (e.g., the hard time limit of PR build jobs, an undersupply of macOS workers), we hardly could fix it properly (i.e., make its result deterministic).  So instead I made it to be automatically retried upto 5 times if it's failed.  Note that it doesn't affect to Linux build jobs.
See also <https://github.com/dahlia/travis-auto-rebuilder>.
=> Automatically rebuild macOS build (upto 5 times) if it's failed

.travis.yml
The previous auto rebuilder parameter (see also #213) tries to retry broken macOS builds regardless whether the Linux job next to them is passed or not.  If a Linux job is not passed either macOS job shouldn't be retried and whole build should be properly fixed instead.  This change the auto rebuilder is triggered subject to the result of a Linux job.
=> Rebuild macOS job only if Linux job is passed

src/Nirum/Targets/Docs.hs
오래된 PR의 먼지를 털어 올립니다.
* 웹폰트가 안 나오는 문제를 수정합니다.
* 타입 이름에 `<code>` 태그를 씌우는 대신 타입에 `<code>` 태그를 씌웁니다.
* 메서드의 리턴 및 예외 정보를 아래에 나오도록 수정합니다.
* 일부 디자인 수정
=> Improve document for statistics

src/Nirum/Targets/Python.hs, test/python/service_test.py
=> #167: Add Client class under Service class

src/Nirum/Targets/Python.hs, test/python/primitive_test.py
In this patch, `ValueError` of deserialization shows all error messages at a time. (closes #168)
```
ValueError: family_name: '404' is not a string.
given_name: '503' is not a string.
```
=> Collapse error messages

CHANGES.md, docs/refactoring.md, docs/serialization.md, src/Nirum/Targets/Python.hs, test/python/primitive_test.py
Fixes #232.  See also *docs/refactoring.md* and *CHANGES.md*.
=> Make record/union deserializers ignore unknown fields

CHANGES.md, docs/refactoring.md, examples/shapes.nrm, src/Nirum/Constructs/DeclarationSet.hs, src/Nirum/Constructs/Identifier.hs, src/Nirum/Constructs/TypeDeclaration.hs, src/Nirum/Parser.hs, src/Nirum/Targets/Docs.hs, src/Nirum/Targets/Python.hs, test/Nirum/Constructs/DeclarationSetSpec.hs, test/Nirum/Constructs/TypeDeclarationSpec.hs, test/Nirum/ParserSpec.hs, test/nirum_fixture/fixture/foo.nrm, test/python/primitive_test.py
=> Optional default tag for union type

CHANGES.md, docs/target/python.md, src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/types.nrm, test/python/serialization_test.py, test/python/setup_test.py, test/serialization/.check, test/serialization/primitive-types/uuid.json, test/serialization/records/unknown-fields.json, test/serialization/sets/duplicate-elements.json, test/serialization/unions/default-tag.json, test/serialization/unions/unknown-fields.json, tox.ini
This PR adds the basic test suite for serialization/deserialization rules suggested by #239.  The format of spec files is quite different from what #239 suggested.  Here's key differences:
-  To make these easier to organize, I intended “one file for one spec” rather than pairing two JSON files for a spec which #239 suggested.
-  I intentionally chose a term *normal* instead of *expected* to make it clear that it's about what is the normal form.
-  During implementing this, I figured out that we need a way to resolve a Nirum type what a spec tests about; Not only `"_type"` field is not enough, it even is not there for some cases (unboxed types based on primitive types, enum types, lists, maps, sets, et cetera; there are a lot more).  So I introduced a distinct `"type"` field for a spec …
=> Serialization test suite

src/Nirum/Targets/Python.hs, src/Nirum/Targets/Python.hs-boot, src/Nirum/Targets/Python/CodeGen.hs, src/Nirum/Targets/Python/TypeExpression.hs, test/Nirum/PackageSpec.hs, test/Nirum/Targets/Python/CodeGenSpec.hs, test/Nirum/Targets/Python/TypeExpressionSpec.hs, test/Nirum/Targets/PythonSpec.hs, test/Nirum/TypeInstance/BoundModuleSpec.hs
As `Nirum.Targets.Python` had been too large to be left as a single module, I divide it into several submodules.  This kind of module dividing could be done more from now on.
Note that I added *Python.hs-boot* file as well.  It's like a header file which consists of forward declarations in C/C++.  With `{-# SOURCE #-}` pragma annotated `import` statements, it breaks a cycle of module dependency.  See also the related chapter in the GHC User's Guide: [*How to compile mutually recursive modules*][1].
[1]: https://downloads.haskell.org/~ghc/8.2.2/docs/html/users_guide/separate_compilation.html#how-to-compile-mutually-recursive-modules
=> Divide Python target into submodules

src/Nirum/Targets/Python.hs, src/Nirum/Targets/Python/Serializers.hs
It's continued work from the previous PR #242.  In the same way to #242, it also doesn't change its behavior nor add any new features, but just extract serializer generators from one monolithic module `Nirum.Targets.Python`.
=> Extract serializer generators from Python target module

.travis.yml, test/python/primitive_test.py
Although there's likely no bugs in generated Python `__hash__()` methods, unit tests for `__hash__()` had been seriously incorrect.
=> Proper unit tests for Python __hash__() behavior

.gitignore, .hlint.yaml, .travis.yml, CHANGES.md, src/Nirum/Targets/Python.hs, src/Nirum/Targets/Python/CodeGen.hs, src/Nirum/Targets/Python/TypeExpression.hs, src/Nirum/Targets/Python/Validators.hs, test/Nirum/Targets/Python/CodeGenSpec.hs, test/Nirum/Targets/Python/TypeExpressionSpec.hs, test/nirum_fixture/fixture/foo.nrm, test/nirum_fixture/fixture/types.nrm, test/python/primitive_test.py, test/python/service_test.py, test/python/validation_test.py, test/serialization/primitive-types/uuid.json, tox.ini
This patch basically deals with a part of #160, with several other changes related to it.
- It makes all generated Pyhon codes completely free from `validate_*()` runtime functions that *nirum-python* library provides.  See also added `Nirum.Targets.Python.Validators` module.
- Besides that, it also adds more validations like range/format checks, e.g., time zone awareness of a `datetime` value.
- Fixes #220.
- On Python 2, `uri` became represented as `basestring` instead of `unicode`, since URI (unlike IRI) is limited to a subset of ASCII character set.
- Cherry-picked two commits from #244.
See also *CHANGES.md*.
=> Make generated Python codes free from validate_*() runtime functions

CHANGES.md, Dockerfile
It's useful when you need networking inside an image.
=> Make Docker image to have CA certificates

CHANGES.md, src/Nirum/Constructs/Declaration.hs, src/Nirum/Constructs/DeclarationSet.hs, src/Nirum/Constructs/TypeDeclaration.hs, test/Nirum/Constructs/DeclarationSetSpec.hs, test/Nirum/Constructs/TypeDeclarationSpec.hs, test/nirum_fixture/fixture/foo.nrm, test/nirum_fixture/fixture/reserved-keyword-enum.nrm, test/nirum_fixture/fixture/reserved-keyword-union.nrm, test/python/primitive_test.py, test/python/setup_test.py
In order to make Nirum IDL more portable to various target languages, I added some more rules to restrict name shadowing.  See also changelog I wrote.
=> Make enum members and union tags to reserve top-level type namespace

CHANGES.md, src/Nirum/Parser.hs, test/Nirum/ParserSpec.hs
Continued from #254.  Now give nicer error message on name duplicates.  Offset line/column number became accurate.
Where the following Nirum code is given:
```nirum
union bar = foo
| bar
| baz;
```
Although the compiler had given the following error message (which refers to inaccurate offset line/column number):
```
examples/a.nrm:5:1:
the facial type name `bar` is duplicated
^
```
It's now like the following:
```
examples/a.nrm:3:13:
the tag name `bar` is duplicated
| bar
^
```
See also the added `"handling name duplications"` test case.
=> Nicer error message on name duplicates

CHANGES.md, docs/annotation.md, docs/target/docs.md, examples/package.toml, package.yaml, src/Nirum/Targets/Docs.hs, test/Nirum/Targets/DocsSpec.hs, test/Nirum/TestFixtures.hs, test/nirum_fixture/package.toml
In order to render a meaningful `<title>`, a new required configuration `targets.docs.title` was added.
=> targets.docs.title config to render <title>

CHANGES.md, src/Nirum/Targets/Docs.hs
Docs now have a sidebar and it shows the table of contents.
=> Show table of contents in the docs sidebar

CHANGES.md, CONTRIBUTING.md, examples/builtins.nrm, src/Nirum/Docs.hs, src/Nirum/Targets/Docs.hs, test/Nirum/DocsSpec.hs, tox.ini
- 7ac8e654db578cce8e2279575e9b1a4171a8ce1f: Added the missing module-level docs.
- f0c3e3033c7ad4fd50f3cd864acb66012a7a1516: Show which tag (if exists) of a union is default.  The `default` keyword on tags is a recently added feature; see also #227 and #13.
- 85aedff1e1d512cb2bd7878308d2c9a6bd807b72: Adjusted on HTML markups; it's about styles and semantics.
- dc13fd9a7bc3bbaa2f014569cb670d7e75e3b977: Require the latest tox version to avoid recent breakage on Python 2.7 builds.  (I guess it's related to the migration from <https://pypi.python.org/> to <https://pypi.org/> but am not sure.)
=> Several improvements on docs target

.travis.yml, CHANGES.md, src/Nirum/Targets/Python.hs, src/Nirum/Targets/Python/CodeGen.hs, src/Nirum/Targets/Python/Deserializers.hs, src/Nirum/Targets/Python/Serializers.hs, src/Nirum/Targets/Python/Validators.hs, test/Nirum/Targets/Python/CodeGenSpec.hs, test/Nirum/Targets/PythonSpec.hs, test/nirum_fixture/fixture/types.nrm, test/python/docs_test.py, test/python/primitive_test.py, test/python/renames_test.py, test/python/serialization_test.py, test/python/service_test.py, test/serialization/primitive-types/date-invalid-formats.json, test/serialization/primitive-types/datetime-invalid-formats.json, test/serialization/primitive-types/datetime.json, test/serialization/primitive-types/uuid-hex.json, test/serialization/records/missing-fields.json, test/serialization/records/non-object.json, test/serialization/unboxed-types/enum.json, test/serialization/unboxed-types/number.json, test/serialization/unboxed-types/record.json, test/serialization/unboxed-types/string.json, test/serialization/unboxed-types/unboxed.json, test/serialization/unboxed-types/union.json, test/serialization/unions/missing-fields.json, test/serialization/unions/missing-tag.json, test/serialization/unions/non-object.json
This PR closes #160.
- Became to generate deserializer code instead of using `deserialize_meta()` function provided by *nirum-python* runtime library.
- In order to verify the correctness of generated deserializers, this PR adds several serialization test cases as well.
- Several common functions among serializers/deserializers/validators/etc were moved to `Nirum.Targets.Python.CodeGen` submodule.
- `InstallRequires` type and functions related to it are merged into `CodeGenContext`.
Please read added logs on *CHANGES.md* as well.
=> Runtime free deserializers

test/nirum_fixture/fixture/foo.nrm, test/nirum_fixture/fixture/name.nrm, test/nirum_fixture/fixture/norm.nrm, test/nirum_fixture/fixture/types.nrm, test/python/serialization_test.py, test/python/setup_test.py, test/serialization/enums/enums-female.json, test/serialization/enums/enums-male.json, test/serialization/identifiers/normalize.json.ignore, test/serialization/map-types/record.json, test/serialization/names/behind_name.json, test/serialization/primitive-types/date.json, test/serialization/records/emit-type.json, test/serialization/records/extra-fields.json, test/serialization/records/option-fields.json, test/serialization/records/option-fields2.json, test/serialization/sets/record.json, test/serialization/unboxed-types/list.json, test/serialization/unboxed-types/set.json, test/serialization/unions/optional-field.json, tox.ini
- Added test suite based on examples of `docs/serialization.md`
- Added `ignoreOrder` option on test suit to test a `set` type or `map` type. Since there are no set-like types in JSON.
- An indicator of the field in `ignoreOrder` has to be [jsonpath][]. It uses [jsonpath-ng][] on Python.
- More test suit has to be added followed pull request. Since there are huge changes of the python deserializer in https://github.com/spoqa/nirum/pull/272.
@dahlia Could you review this PR?
[jsonpath]: http://jsonpath.com/
[jsonpath-ng]: https://pypi.org/project/jsonpath-ng/
=> Add test suite based on examples of docs/serialization.md

CHANGES.md, src/Nirum/Targets/Python.hs, test/Nirum/Targets/PythonSpec.hs, test/python/docs_test.py, test/python/primitive_test.py
- Became to use [`Text.Blaze.Markup`][1] type instead of [`Data.Text.Text`][2] type for `CompileResult Python`.  Duplicated `toStrict $ renderText $ ...` things were gone.
- Became to use Heterocephalus templating instead of Perl-style `qq` quasiquoter to render Python classes for service types.
- The metadata field `__nirum_schema_version__` was also gone as it has never been used.
[1]: https://www.stackage.org/haddock/lts-10.7/blaze-markup-0.8.2.0/Text-Blaze.html#t:Markup
[2]: https://www.stackage.org/haddock/lts-10.7/text-1.2.2.2/Data-Text.html#t:Text
=> Use Markup for Python CompileResult

CHANGES.md, docs/serialization.md, examples/builtins.nrm, examples/pdf-service.nrm, src/Nirum/Constructs/Module.hs, src/Nirum/Constructs/TypeDeclaration.hs, src/Nirum/Targets/Python/Deserializers.hs, src/Nirum/Targets/Python/Serializers.hs, src/Nirum/Targets/Python/TypeExpression.hs, src/Nirum/Targets/Python/Validators.hs, test/Nirum/Targets/Python/TypeExpressionSpec.hs, test/nirum_fixture/fixture/foo.nrm, test/nirum_fixture/fixture/types.nrm, test/python/primitive_test.py
https://github.com/spoqa/nirum/issues/126
=> Rename uri to url (uri remains deprecated)

src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/service_test.py
According to the serialization specification, method parameters that have an optional type should can be omitted and treated as `None` if omitted.  As this behavior was missing from the previous PR #278, this patch fixes that.
=> Make optional parameters omittable

CHANGES.md, src/Nirum/Constructs/Module.hs, test/nirum_fixture/fixture/foo.nrm, test/python/primitive_test.py, test/python/validation_test.py
Close https://github.com/spoqa/nirum/issues/126
=> Completely deprecate uri

CHANGES.md, Dockerfile
Building the docker image is failing with an error message ("(ConnectionFailure Network.BSD.getProtocolByName: does not exist (no such protocol name: tcp))"). I think the reason why the build is failing is that `minideb:jessie` which is the base image of nirum lacks the netbase package.
So I install it on Dockerfile.
See also, below links.
- https://github.com/dahlia/nirum/commit/c20d20653740336ce1fecb6b82b69d8bd4eb0c89
- https://github.com/commercialhaskell/stack/issues/2372#issuecomment-234113085
=> minideb:jessie image lacks netbase

.hlint.yaml, package.yaml, src/Nirum/Cli.hs, src/Nirum/Parser.hs, src/Nirum/Targets/Docs.hs, src/Nirum/Targets/Python.hs, src/Nirum/Targets/Python/CodeGen.hs, stack.yaml
- Since *turtle-1.5.9* is included to `lts-11.15`, remove *turtle-1.5.4* from `extra-deps`.  (See also the removed comment above it.)
- *hlint* is also upgraded to 2.1.6, and it introduces more suggestions (and a bug).  The most of changes are due to this, and an ignore is also added in order to work around *hlint*'s bug.  See the issue linked in a comment.
=> Upgrade to Stackage LTS Haskell 11.15

.hlint.yaml, CHANGES.md, README.md, appveyor.yml, package.yaml, stack.yaml
- GHC is upgraded from 8.2.2 to 8.4.3.
- A temporary HLint configuration (made by the PR #286) to ignore “Use const” hint due to ndmitchell/hlint#506 is gone as newer HLint version that the bug was fixed is included to `lts-12.0`.
=> Upgrade to Stackage LTS Haskell 12.0

.travis.yml, CHANGES.md, app/nirum-docs.hs, docs/target/docs.md, examples/package.toml, src/Nirum/Cli.hs, src/Nirum/Package/Metadata.hs, src/Nirum/Targets.hs, src/Nirum/Targets/Docs.hs, test/Nirum/TargetsSpec.hs
[![A screenshot of nirum.org website](https://user-images.githubusercontent.com/12431/44055008-18d26240-9f7f-11e8-947c-8e1751ccf37c.png)](https://nirum.org/)
This patchset purposes to publish the [nirum.org](https://nirum.org/) website using the docs target.  There are three groups of patches:
- New features into the docs target like `style` option.  These are useful for designing look and feel of the website.
- The *app/nirum-docs.hs* script to generate the docs for the compiler itself, and several adjustments on internal APIs in order to enable the script.
- A new process on Travis CI to automatically build and upload the website for every release (tag).
Note that the sample website is already deployed to [nirum.org](https://nirum.org/).  It's served by GitHub Pages, and the generated …
=> Build the nirum.org website using docs target

src/Nirum/Docs/Html.hs
When compiler generate `CodeBlock`, it doesn't escape its code. So if code contain HTML special characters, compiled into HTML tag. 
I escaped `code'` so that `code'` is not rendered to HTML elements.
Closes #301
=> Escape code blocks

docs/package.md, docs/refactoring.md, docs/serialization.md, docs/tutorial.md
Fixed typo on 
+ docs/package.md
+ docs/refactoring.md
+ docs/serialization.md
+ docs/tutorial.md
=> Fixed typo on some docs

CHANGES.md, app/nirum-docs.hs, docs/target/docs.md, src/Nirum/Package/Metadata.hs, src/Nirum/Targets/Docs.hs
Usage:
```toml
[targets.docs]
title = "Nirum Examples"
[[targets.docs.opengraphs]]
tag = "og:url"
content = "https://nirum.org"
[[targets.docs.opengraphs]]
tag = "og:title"
content = "Nirum Examples"
```
Closes: #283
=> Added `opengraphs` option for open graph tags on docs

CHANGES.md, src/Nirum/Targets/Docs.hs
=> Add syntax highlighting for doc target

examples/shapes.nrm
- fix typo from `reocrd` to `record`
=> Fix typo in shapes.nrm

src/Nirum/Targets/Docs.hs
A picture is worth a thousand words:
=> Make version on docs visually distinct from package name

src/Nirum/Targets/Python/Deserializers.hs
- Add missing `#{builtins}` to use at except clause of python templates.
=> Add missing to use builtins in python template

CHANGES.md, src/Nirum/Package/Metadata.hs
=> Open package.toml file with UTF8 locale

CHANGES.md, src/Nirum/Targets/Docs.hs
=> Add nirum syntax highlighting to docs target

.travis.yml, package.yaml
This fixes the build error #325.  Although there has been a `sed` script intending the same trick, it actually hadn't worked.  I changed it to replace [`-Werror`][1] with [`-Wwarn`][2] rather than remove it, because it can lead to an invalid YAML.  For example, given the following YAML:
```yaml
ghc-options:
- -Werror
other-options: ...
```
if the item `- -Werror` is removed it becomes invalid:
```yaml
ghc-options:  # YAML syntax disallows this
other-options: ...
```
Also, although we license the Nirum compiler under “GPL 3.0 or higher” not “GPL 3.0 only,” as `GPL-3` means the latter, I changed it to [`GPL-3.0-or-later`][3].  (Note that [since Cabal 2.2 `license` field supports SPDX syntax.][4])
[1]: https://downloads.haskell.org/~ghc/8.4.3/docs/html/users_guide/using-warnings.html#ghc-flag …
=> Trim -Werror option before uploading to Hackage

CHANGES.md, src/Nirum/Targets/Python.hs, test/nirum_fixture/fixture/foo.nrm, test/python/annotation_test.py
Added `__nirum_annotations__` static field on generated **union** type python classes.
Issue #273
=> Add annotation metadata on generated union type classes
