nirum-lang/nirum

- .travis.yml
- README.md
For OSX Nightly build. Closes #47.
> Travis for OSX

- src/Nirum/Parser.hs
- test/Nirum/ParserSpec.hs
> Proper syntax error position for missing semicolon

- src/Nirum/Targets/Python.hs
- test/Nirum/Targets/PythonSpec.hs
> Generate tag has no field properly

- README.md
- nirum.cabal
- Update synopsis and description to follow README.md's.
- Adjust casing of README.md's “Getting started” title for consistency.
> Adjust front matter

- .travis.yml
- test.sh
- tox.ini
This fixes PR #94's broken build.
> Upgrade nirum-python to 0.3.7

- src/Nirum/Targets/Python.hs
- test/python/primitive_test.py
> Make the service include version information

- stack.yaml
They released a new LTS Haskell.
<https://www.stackage.org/lts-8.5>
> Upgrade to Stackage LTS Haskell 8.5

- README.md
See also: <https://github.com/Aaronepower/tokei#badges>.
> Count lines of code using Tokei

- README.md
> Link related projects & tools

- stack.yaml
> Upgrade to Stackage LTS Haskell 8.11

- .travis.yml
- README.md
- package.yaml
- src/Main.hs
> Include code-cov options

- docs/package.md
- src/Nirum/Package/Metadata.hs
Wrote docs about `description` field (added by #174).
> Docs about description field

- .travis.yml
This aims to fix the currently broken Linux build on Travis CI.
> Fix installation of Python toolchain

- src/Nirum/Constructs/Service.hs
- src/Nirum/Parser.hs
- src/Nirum/Targets/Docs.hs
- src/Nirum/Targets/Python.hs
- test/Nirum/Constructs/ServiceSpec.hs
- test/Nirum/Constructs/TypeDeclarationSpec.hs
- test/Nirum/ParserSpec.hs
- test/Nirum/Targets/PythonSpec.hs
- test/nirum_fixture/fixture/foo.nrm
- test/python/service_test.py
> Implement omit return value

- appveyor.yml
> Fix broken tox py27 env on AppVeyor

- lint.sh
- src/Nirum/Parser.hs
- src/Nirum/Targets/Docs.hs
- src/Nirum/Targets/Python.hs
- test/Nirum/Constructs/TypeDeclarationSpec.hs
> Fix Haskell style scanner

- .dockerignore
- .gitignore
- .travis.yml
- codecov.yml
- stack.yaml
use forked codecov-haskell branch
> Fix code cov

- README.md
> Add VS Code syntax highlighter in README.md

- docs/serialization.md
- docs/transport.md
This replaces #261 which closed.
Write a basic specification about the current HTTP/JSON transport.  [Preview is here.](https://github.com/dahlia/nirum/blob/4bba4ede1765e6d1dbab2aafeb262a0e33f66620/docs/transport.md)
> Transport docs

- CHANGES.md
- src/Nirum/Targets/Python.hs
- src/Nirum/Targets/Python/CodeGen.hs
- src/Nirum/Targets/Python/Validators.hs
- test/nirum_fixture/fixture/foo.nrm
- test/python/service_test.py
Generate serializers and deserializers for service methods' parameters, return types, and error types.
See also changelogs.
> Serializers and deserializers for service methods

- CONTRIBUTING.md
Add more contribution guide about
- Installing lint on git hook.
- Writing `CHANGES.md`.
> Write about lint and chagelog on CONTRIBUTING.md

- Dockerfile
- lint.sh
This fixes SC2230, DL4006, DL3025.
> Fix Shellcheck and Hadolint

- .gitignore
- src/Nirum/Targets/Docs.hs
The above becomes like the below:
> Fix two separators being sticked together on docs

- CHANGES.md
- app/nirum-docs.hs
- src/Nirum/Targets/Docs.hs
> Add anchor links to headings
